MVC/Labo3/e_learning/Controllers/EtudiantController.cs
using e_learning.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI.WebControls;

namespace e_learning.Controllers
{
    public class EtudiantController : Controller
    {
        ElearningDbDataContext db = new ElearningDbDataContext();

        // GET: Etude
        public ActionResult IndexEtudiant()
        {
            return View();
        }

        /// <summary>
        /// changement pour le mot de passe et le username du nouveau etudiant
        /// </summary>
        /// <returns></returns>
        public ActionResult CompleteRegistration()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CompleteRegistration(etudiant e)
        {
            try
            {
                var compare = (from x in db.etudiant where x.username == Session["username"].ToString() && x.password == Session["password"].ToString() select x).FirstOrDefault();
                if (compare!=null)
                {
                    etudiantMode gw = new etudiantMode();

                    if (gw.insertE(e))
                    {
                        return RedirectToAction("IndexEtudiant");
                    }
                }
            }
            catch (Exception)
            {

                ViewBag.msg = "Utilisateur non existant! :-(";
            }

            return View();
        }

        /// <summary>
        /// inscription de l'etudiant a un cours
        /// </summary>
        /// <returns> une confirmation</returns>
        public ActionResult inscription(int reportID)
        {
            demande_inscription di =new demande_inscription();

            di.id_cours = reportID;
            di.id_etudiant = Convert.ToInt32(Session["Id_etudiant"]);
            di.accepter = false;

            demandeMode dm = new demandeMode();
  
            if (dm.demandeInscription(di))
            {
                ViewBag.msg = "Votre demande a été envoyé et sera traitée sous peu!";
            }
            else
            {
                ViewBag.msg = "Vous etes deja enregistre pour ce cours";
            }

            return View();

        }

        [HttpPost]
        public ActionResult inscription()
        {
            return View();

        }

        public ActionResult showdemande(etudiant e)
        {

            
            var listdemande = from dem in db.demande_inscription where dem.id_etudiant==Convert.ToInt32(Session[0]) && dem.accepter==true select dem;

            ViewBag.title = "Inscription";
            ViewBag.message = "LISTE DE VOS COURS";

            return View(listdemande);
        }
          

        public ActionResult showcours()
        {
            
            var listcours = from crs in db.cours select crs;

            ViewBag.title = "Cours diponible";
            ViewBag.message = "LISTE DES COURS DISPONIBLE";

            return View(listcours);
        }

        public ActionResult sendmsg()
        {

            return View();
        }


        [HttpPost]
        public ActionResult sendmsg(inbox e)
        {
            e.Id_etudiant =Convert.ToInt32(Session["Id_etudiant"]);

            try
            {
                    db.inbox.InsertOnSubmit(e);
                    db.SubmitChanges();

                ViewBag.msg = "Merci! Vos commentaires nous sont importants.";
                return View();
            }
            catch (Exception)
            {
                ViewBag.Message = "Vous devez remplir tous les champs!";
                return View();
            }

        }


        public ActionResult readmessage()
        {

            var msg = (from x in db.inbox where x.Id_etudiant == Convert.ToInt32(Session["Id_etudiant"]) select x).ToList();
            return View(msg);
        }

        public ActionResult about()
        {

            return View();
        }


        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Login", "Home");
        }
    }
}

MVC/Labo3/e_learning/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Guimo E-Learning</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/Content/elerning.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-bottom">
        <div class="container">
            <a class="navbar-brand" href="#">E-Learning</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Content -->
    <section>
        <div class="container-fluid" id="home1">
            <div class="row">
                <div class="col-lg-3">
                    <h1>Bienvenue à E-Learning!</h1>
                    <p>
                        Dans le cadre de nos efforts continus afin d’améliorer nos services tout en reconnaissant qu’Internet
                        constitue la principale source d’information pour la plupart de nos clients, nous sommes heureux de
                        présenter un site Web qui affiche un air nouveau et comporte une meilleure fonctionnalité.
                    </p>
                </div>
                <div class="col-lg-4">

                </div>
                <div class="col-lg-3" id="logs">
                    @RenderBody()
                </div>
                <div class="col-lg-1">
                    <!--Facebook-->
                    <a href="" type="button" class="btn-floating btn-lg btn-fb"><i class="fa fa-facebook"></i></a>
                    <!--Twitter-->
                    <a href="" type="button" class="btn-floating btn-lg btn-tw"><i class="fa fa-twitter"></i></a>
                    <!--Instagram-->
                    <a href="" type="button" class="btn-floating btn-lg btn-ins"><i class="fa fa-instagram"></i></a>
                    <!--Youtube-->
                    <a href="" type="button" class="btn-floating btn-lg btn-yt"><i class="fa fa-youtube"></i></a>
                    <!--Comments-->
                    <a href="" type="button" class="btn-floating btn-lg btn-comm"><i class="fa fa-comments"></i></a>
                    <!--Email-->
                    <a href="" type="button" class="btn-floating btn-lg btn-email"><i class="fa fa-envelope"></i></a>
                </div>

            </div>
        </div>
    </section>
    <!-- Bootstrap core JavaScript -->
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
</body>
</html>

MVC/Labo3/e_learning/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>E-Learning</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="~/Content/etudiantStyle.css" rel="stylesheet" />
</head>
<body>
    @*bare de navigatio*@
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><img src="~/Images/e_logo.png" width="45" height="25" /></a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#">Cours</a></li>
                    <li><a href="#">Mes cours</a></li>
                    <li><a href="#">Contact</a></li>
                    <li><a href="#">About</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>

    <footer class="container-fluid text-left">
        <p>Guimo E-learning</p>
    </footer>

</body>
</html>

MVC/Labo3/e_learning/Views/Shared/_LayoutEnseignant.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>E-Learning</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="~/Content/etudiantStyle.css" rel="stylesheet" />
</head>
<body>
    @*bare de navigatio*@
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><img src="~/Images/e_logo.png" width="45" height="25" /></a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#">Cours</a></li>
                    <li><a href="#">Mes cours</a></li>
                    <li><a href="#">Contact</a></li>
                    <li><a href="#">About</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>

    <footer class="container-fluid text-left">
        <p>Guimo E-learning</p>
    </footer>

</body>
</html>

MVC/Labo3/e_learning/Views/Shared/_LayoutEtudiant.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>E-Learning</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="~/Content/etudiantStyle.css" rel="stylesheet" />
</head>
<body>
    @*bare de navigatio*@
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><img src="~/Images/e_logo.png" width="45" height="25" /></a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "indexEtudiant", "Etudiant")</li>
                    <li>@Html.ActionLink("Cours", "showcours", "Etudiant")</li>
                    <li>@Html.ActionLink("Mes cours", "showdemande", "Etudiant")</li>
                    <li>@Html.ActionLink("Contact", "sendmsg", "Etudiant")</li>
                    <li>@Html.ActionLink("Inbox", "readmessage", "Etudiant")</li>
                    <li>@Html.ActionLink("About", "about", "Etudiant")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Logout", "LogOut", "Etudiant")</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container" id="main">
        @RenderBody()
    </div>

    <footer class="container-fluid text-left">
        <p>Guimo E-learning</p>
    </footer>

</body>
</html>